### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by mano-mykingdom**
1. https://github.com/jfeinstein10/SlidingMenu/issues/680- (if windowDrawsSystemBarBackgrounds is set to false, won't be able set status bar, so `setSystemUiVisibility(SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);` is used)
2. #159

### CODE REVIEW

**Comment by viezel** [comment]
Hi there,
Thanks for the PR :)

Please dont update classpath, .project, build.properties
Also there are no reason to update to 4.0.0 as I see it. Why do you need to do that ?

**Comment by mano-mykingdom** [comment]
Hi @viezel When I compile using 3.1.3.GA, I get the following. May I know what I'm missing here?

```
Buildfile: /Users/esimacmini2013/MJ/NappDrawer/android/build.xml

python.set.exec:

python.check:
     [echo] Testing for Python
     [exec] Python 2.7.6

init:

process.annotations:
    [javac] Compiling 9 source files to /Users/esimacmini2013/MJ/NappDrawer/android/build/classes
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/chrisrenke/drawerarrowdrawable/DrawerArrowDrawable.java:37: cannot find symbol
    [javac] symbol  : class DrawerLayout
    [javac] location: package android.support.v4.widget
    [javac] import static android.support.v4.widget.DrawerLayout.DrawerListener;
    [javac]                                        ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/chrisrenke/drawerarrowdrawable/DrawerArrowDrawable.java:37: static import only from classes and interfaces
    [javac] import static android.support.v4.widget.DrawerLayout.DrawerListener;
    [javac] ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/DrawerProxy.java:138: cannot find symbol
    [javac] symbol  : class Bundle
    [javac] location: class dk.napp.drawer.DrawerProxy
    [javac] 	public void windowCreated(TiBaseActivity activity, Bundle savedInstanceState) {
    [javac] 	                                                   ^
    [javac] org/appcelerator/titanium/view/TiUIView.class(org/appcelerator/titanium/view:TiUIView.class): warning: Cannot find annotation method 'value()' in type 'android.annotation.SuppressLint': class file for android.annotation.SuppressLint not found
    [javac] org/appcelerator/titanium/TiApplication.class(org/appcelerator/titanium:TiApplication.class): warning: Cannot find annotation method 'value()' in type 'android.annotation.SuppressLint'
    [javac] Note: [KrollBindingGen] Running Kroll binding generator.
    [javac] Note: [KrollBindingGen] Succesfully loaded existing binding data: /Users/esimacmini2013/MJ/NappDrawer/android/build/generated/json/org/appcelerator/titanium/bindings/nappslide.json
    [javac] Note: [KrollBindingGen] Found binding for proxy Drawer
    [javac] Note: [KrollBindingGen] Found binding for module Nappdrawer
    [javac] Note: [KrollBindingGen] Generating JSON: /Users/esimacmini2013/MJ/NappDrawer/android/build/generated/json/org/appcelerator/titanium/bindings/nappslide.json
    [javac] warning: The following options were not recognized by any processor: '[kroll.checkTiContext]'
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/chrisrenke/drawerarrowdrawable/DrawerArrowDrawable.java:37: cannot find symbol
    [javac] symbol  : class DrawerLayout
    [javac] location: package android.support.v4.widget
    [javac] import static android.support.v4.widget.DrawerLayout.DrawerListener;
    [javac]                                        ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/chrisrenke/drawerarrowdrawable/DrawerArrowDrawable.java:37: static import only from classes and interfaces
    [javac] import static android.support.v4.widget.DrawerLayout.DrawerListener;
    [javac] ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/DrawerProxy.java:138: cannot find symbol
    [javac] symbol  : class Bundle
    [javac] location: class dk.napp.drawer.DrawerProxy
    [javac] 	public void windowCreated(TiBaseActivity activity, Bundle savedInstanceState) {
    [javac] 	                                                   ^
    [javac] org/appcelerator/titanium/view/TiUIView.class(org/appcelerator/titanium/view:TiUIView.class): warning: Cannot find annotation method 'value()' in type 'android.annotation.SuppressLint': class file for android.annotation.SuppressLint not found
    [javac] org/appcelerator/titanium/TiApplication.class(org/appcelerator/titanium:TiApplication.class): warning: Cannot find annotation method 'value()' in type 'android.annotation.SuppressLint'
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/Drawer.java:314: cannot find symbol
    [javac] symbol  : method getSupportActionBar()
    [javac] location: class org.appcelerator.titanium.TiBaseActivity
    [javac] 			activity.getSupportActionBar().setHomeAsUpIndicator(drawerArrowDrawable);
    [javac] 			        ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/Drawer.java:315: cannot find symbol
    [javac] symbol  : method getSupportActionBar()
    [javac] location: class org.appcelerator.titanium.TiBaseActivity
    [javac] 			activity.getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    [javac] 			        ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/Drawer.java:317: cannot find symbol
    [javac] symbol  : method getSupportActionBar()
    [javac] location: class org.appcelerator.titanium.TiBaseActivity
    [javac] 			activity.getSupportActionBar().setHomeAsUpIndicator(0);
    [javac] 			        ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/DrawerProxy.java:38: dk.napp.drawer.DrawerProxy is not abstract and does not override abstract method windowCreated(org.appcelerator.titanium.TiBaseActivity) in org.appcelerator.titanium.TiActivityWindow
    [javac] public class DrawerProxy extends TiWindowProxy implements TiActivityWindow
    [javac]        ^
    [javac] /Users/esimacmini2013/MJ/NappDrawer/android/src/dk/napp/drawer/DrawerProxy.java:137: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] 8 errors
    [javac] 2 warnings

BUILD FAILED
/Users/esimacmini2013/Library/Application Support/Titanium/mobilesdk/osx/3.1.3.GA/module/android/build.xml:163: Compile failed; see the compiler error output for details.

Total time: 1 second
```

**Comment by mano-mykingdom** [comment]
As far I know, it is possible to compile with `3.1.3.GA` as because the constructor of `TiWindowProxy` class is different from `4.0.0.GA`.

**Comment by viezel** [comment]
HI @mano-mykingdom  
was it possible to do with 3.1.3 ?
