### ISSUE TITLE
Unable to compile with Ti SDK 3.2.0

### ISSUE THREAD

**Issue by staticdreams** [viezel/NappDrawer#36]
When building with an app the latest 3.2.0 Titanium SDK compiler fails:

```
[TRACE] :  Undefined symbols for architecture i386:
[TRACE] :    "_OBJC_CLASS_$_CustomMMDrawerController", referenced from:
[TRACE] :        objc-class-ref in libdk.napp.drawer.a(DkNappDrawerDrawer.o)
[TRACE] :  ld: symbol(s) not found for architecture i386
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] :  ** BUILD FAILED **
```

Prior 3.2.0 NappDrawer worked just fine.
